name: Gestion de Turnos en Slack

# Sección "on" para programar los horarios de ejecución de acuerdo a los cambios de turno
on:
  schedule:
    # Turnos de lunes a jueves
    - cron: '0 9 * * 1-4'   # 09:00 AM (Turno de Zaira)
    - cron: '17 10 * * 1-4'  # 10:17 AM (Turno de Nancy)
    - cron: '34 11 * * 1-4'  # 11:34 AM (Turno de Andres)
    - cron: '51 12 * * 1-4'  # 12:51 PM (Turno de Julio)
    - cron: '08 14 * * 1-4'  # 02:08 PM (Turno de Andrea)
    - cron: '25 15 * * 1-4'  # 03:25 PM (Turno de Lucy)
    - cron: '42 16 * * 1-4'  # 04:42 PM (Turno de Armando)

    # Turnos del viernes
    - cron: '0 9 * * 5'      # 09:00 AM (Turno de Zaira)
    - cron: '17 10 * * 5'     # 10:17 AM (Turno de Nancy)
    - cron: '34 11 * * 5'     # 11:34 AM (Turno de Julio)
    - cron: '51 12 * * 5'     # 12:51 PM (Turno de Lucy)
    - cron: '08 14 * * 5'     # 02:08 PM (Turno de Andrea)
    - cron: '25 15 * * 5'     # 03:25 PM (Turno de Andres)
    - cron: '42 16 * * 5'     # 04:42 PM (Turno de Armando)

jobs:
  slack-turnos:
    runs-on: ubuntu-latest  # O el entorno que prefieras usar

    steps:
    # Paso 1: Checkout del repositorio
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    # Paso 2: Configuración de Python
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Paso 3: Instalar dependencias necesarias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz

    # Paso 4: Ejecutar el script de Python para gestionar los turnos en Slack
    - name: Ejecutar script de turnos en Slack
      run: |
        python turnos_slack.py

      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}  # Token de Slack almacenado en GitHub Secrets
